### ISSUE TITLE
Error installing mongodb on Amazon Linux AMI 2018.03.0 (ami-6b8cef13)

### ISSUE THREAD

**Issue by dbsrv** [UnderGreen/ansible-role-mongodb#107]
Error occurred on step:
TASK [ansible-role-mongodb : Install MongoDB package]
```
"msg": "https://repo.mongodb.org/yum/redhat/latest/mongodb-org/3.6/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

Solution:
I had to create vars/Amazon.yml (copied from vars/RedHat.yml), replaced "redhad" with "amazon", and also "$releasever" with "2013.03"  to resolve the issue.
```
mongodb_repository:
  "3.2": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.2/$basearch/"
  "3.4": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.4/$basearch/"
  "3.6": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/$basearch/"
...
```
Is there a better way to resolve this?

**Comment by UnderGreen** [comment]
Way will be more complicated, because you should change tasks to use variables from Amazon.yaml. Amazon is a `ansible_distribution` var, not a `ansible_os_family`.  But, anyway, you think right, I don't know better and simple ways.

**Comment by dbsrv** [comment]
Fyi,
additional changes in **tasks/mms-agent.yml** to install mms agent in Amazon Linux.

Added "Amazon" in conditional.

L11: when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'
L22: when: mongodb_mms_agent_loaded.changed and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon')

**Comment by Freyert** [comment]
Copy and paste solution for anyone encountering this issue:

```yaml
 - name: install mongo
   hosts: mongo
   become: true
   roles:
     - role: undergreen.mongodb
       mongodb_repository: # [Can always override role variables by passing in.](1)
           "3.2": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.2/$basearch/"
           "3.4": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.4/$basearch/"
           "3.6": "https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/$basearch/"
```

[1]: https://docs.ansible.com/ansible/2.5/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
