### ISSUE TITLE
Can't connect using mongo from vagrant instance.

### ISSUE THREAD

**Issue by jondkelley** [UnderGreen/ansible-role-mongodb#109]
I've validated I can telnet to the port I've forwarded from vagrant (localhost:27018) but the mongo client hangs trying to connect using mongo --host 127.0.0.1 --port 27018. This is also true using mongohub.

Vagrantfile port forward

```  config.vm.network "forwarded_port", guest: 27017, host: 27018```

On parent host:
```mongo --host 127.0.0.1 --port 27018
MongoDB shell version v3.6.5
connecting to: mongodb://127.0.0.1:27018/
```

Inside vagrant vm:
```
[root@localhost vagrant]# mongo --host 127.0.0.1 --port 27017
MongoDB shell version v3.6.5
connecting to: mongodb://127.0.0.1:27017/
MongoDB server version: 3.6.5
Welcome to the MongoDB shell.
For interactive help, type "help".
```

Here's my vars, I'm assuming mongodb_security_authorization: "disabled" is the relevant bits to allow unauthorized remote access.

The vars, run against Centos6 vm:
  ```
  vars:
    mongodb_package: mongodb-org
    mongodb_version: "3.6"
    mongodb_pymongo_from_pip: true
    mongodb_user_update_password: "on_create"
    mongodb_manage_service: true
    mongodb_net_bindip: 127.0.0.1
    mongodb_net_http_enabled: false
    mongodb_net_ipv6: false
    mongodb_net_maxconns: 65536
    mongodb_net_port: 27017
    mongodb_processmanagement_fork: false
    mongodb_security_authorization: "disabled"
    mongodb_storage_dbpath: /var/lib/mongo
    mongodb_storage_engine: mmapv1
    mongodb_storage_quota_enforced: false
    mongodb_storage_quota_maxfiles: 8
    mongodb_storage_smallfiles: true
    mongodb_storage_journal_enabled: true
    mongodb_storage_prealloc: true
    mongodb_systemlog_destination: "file"
    mongodb_systemlog_logappend: true
    mongodb_systemlog_path: /var/log/mongodb/{{ mongodb_daemon_name }}.log
    mongodb_replication_replset: xxx
    mongodb_replication_replindexprefetch: "all"
    mongodb_replication_oplogsize: 1024
    mongodb_set_parameters: { "enableLocalhostAuthBypass": "true", "authenticationMechanisms": "SCRAM-SHA-1,MONGODB-CR" }
    mongodb_mms_agent_pkg: https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-manager-latest.x86_64.rpm
    mongodb_mms_group_id: "xxx"
    mongodb_mms_api_key: "xxx"
    mongodb_mms_base_url: https://mms.mongodb.com
    mongodb_logrotate: true
    mongodb_logrotate_options:
      - compress
      - copytruncate
      - daily
      - dateext
      - rotate 7
      - size 10M
    mongodb_user_admin_name: useradmin
    mongodb_user_admin_password: "xxx"
    mongodb_root_admin_name: root
    mongodb_root_admin_password: "xxx"
```
