### ISSUE TITLE
Can't install mongodb 4.0 on ubuntu 18

### ISSUE THREAD

**Issue by usefree** [UnderGreen/ansible-role-mongodb#163]
using playbook
```
---
- hosts: mongo-arbiter
  gather_facts: yes
  roles:
  - role: ansible-role-mongodb
    vars:
      mongodb_package: mongodb
      mongodb_version: "4.0"
      mongodb_user: mongodb
      mongodb_daemon_name: mongodb
      mongodb_net_bindip: "{{ ansible_default_ipv4.address }}"
      mongodb_net_port: 27019
      mongodb_storage_dbpath: /opt/mongodb
      mongodb_storage_dirperdb: true
      mongodb_storage_engine: "wiredTiger"
      mongodb_storage_journal_enabled: true
      mongodb_systemlog_destination: "file"
      mongodb_systemlog_logappend: true
      mongodb_systemlog_path: /var/log/mongodb/{{ mongodb_daemon_name }}.log
      mongodb_replication_replset: test
```

receive mongo 3.6 installed.
If try to replace "mongodb_package: mongodb" with "mongodb_package: mongodb-org" - receive error 
```
mongodb_version variable should be '3.6' or '4.0' and mongodb_package should be 'mongodb' for Ubuntu 18.04
```
May be, when it is mongodb-org package defined for Ubuntu 18 - it should add repository (as described [here](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/) ) and try to install, instead of sending error?
