### ISSUE TITLE
Tasks in install.debian.yml when using tags aren't executed

### ISSUE THREAD

**Issue by HugoPoi** [UnderGreen/ansible-role-mongodb#175]
When you use `undergreen.mongodb` and you use the `--tags mongodb`, the task `Include OS-specific variables` and all tasks in `install.debian.yml` are NOT executed, resulting a very different behavior.

Also there is lot of `include` aka `include_tasks` but I'm not sure about the usage but in the documentation it seems tags aren't applied to included tasks.
May be need to use this syntax
```
- name: Apply tags to tasks within included file
  include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - always
```
