### ISSUE TITLE
Configuring users before configuring mongod

### ISSUE THREAD

**Issue by duhast** [UnderGreen/ansible-role-mongodb#19]
Hi,
I'm curious why the role sets up users _before_ Mongo gets configured?
I mean the fact `auth_initialization.yml` tasks are called before `Create mongodb user`, `Configure mongodb`, and so on...
In my vision, the `mongod` should be configured first. Any comments?

I'm confused by this for a few weeks, but it was ok as long as I was setting up single mongo instance. Now I'm setting up a replica set and it fails because `auth_initialization.yml` tries to connect to a replica set, but `mongod` instances are not yet configured to run in a replication mode.

> msg: unable to connect to database: No replica set members available for replica set name "myRep"

Or I'm doing something wrong?

**Comment by duhast** [comment]
Btw, more info in readme about configuring replica set would be greatly appreciated.

**Comment by UnderGreen** [comment]
> In my vision, the mongod should be configured first. Any comments?

There is very big problem:
If you set up `auth = yes`, after reloading configuration you will need user with root role for initialize RS. But you don't have this user. I did't find i right way(manual way I know, but automatic is impossible) to configure RS and auth, where these options used together.
And if you configured RS before auth, you can't configure auth on local node, because mongo will say you - I need a master node!

**Comment by UnderGreen** [comment]
please provide more info(overrided variables, OS)

**Comment by duhast** [comment]
Yeah, it seems to be complicated to automate. I've played around for several hours with no luck, so for now I've decided to stick with a single mongod instance, no replication.

Thanks for the update @UnderGreen.
Closing the issue as you have answered my question.

**Comment by UnderGreen** [comment]
I spent severals day with no luck, when I tried to automate this.

**Comment by MrMMorris** [comment]
so I just came across this lovely role after giving up trying to automate replication with Docker (running into similar "need to authenticate to initiate" problems). I was wondering if you could clarify what I need to do to get replication going with auth. Do I just need to manually authenticate and rs.initiate()? Or does this role not allow `auth = yes` with a replication set at all?

**Comment by duhast** [comment]
Finally, I've came to the following ugly, but working recipe. I'm running ansible playbook several times.

#### First run
With `mongodb_conf_auth: true` and `mongodb_conf_replSet: false`. This does the initial installation, configures DB path, etc., adds users to Mongo, creates local facts and restarts Mongo.

#### Second run
With `mongodb_conf_auth: false` and `mongodb_conf_replSet: myReplica`. This prepares mongo to work in a replica set by rewriting `/etc/mongod.config` and restarts Mongo. Then the role fails on 
> TASK: [librarian_roles/greendayonfire.mongodb | Replication configuration without auth] ***

with the following error: 
> pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()"

And this sounds right, because the replica set is not initiated yet.
Then I'm connecting to my primary node with authentication (yes, the auth is turned off, but nevertheless `mongod` won't let you run commands without authorization):
```bash
mongo -u root -p xxXXxxxXXxxXX 10.10.13.22/admin
```
And initiating replica set:
```
> rs.initiate()
{
	"info2" : "no configuration explicitly specified -- making one",
	"me" : "10.10.13.22:27017",
	"info" : "Config now saved locally.  Should come online in about a minute.",
	"ok" : 1
}
```

#### Third run
With `mongodb_conf_auth: true` and all replica-related coonfiguration set:
```yaml
mongodb_conf_replSet: myReplica
mongodb_login_host: "{{ hostvars['db0.myapp.lan'].ansible_eth1.ipv4.address }}" #Primary node
mongodb_replication_params:
  - host_name: "{{ hostvars['db1.myapp.lan'].ansible_eth1.ipv4.address }}"
    host_port: "{{ mongodb_conf_port }}"
    host_type: replica
  - host_name: "{{ hostvars['db1.myapp.lan'].ansible_eth1.ipv4.address }}"
    host_port: "{{ mongodb_conf_port }}"
    host_type: replica
  - host_name: "{{ hostvars['web1.myapp.lan'].ansible_eth1.ipv4.address }}"
    host_port: 27018
    host_type: arbiter
```
On this run, the replica hosts are getting added to `rs.config()` on the primary node and the playbook succeeds for the primary node. Secondary nodes are failing on creating users because the role tries to connect to a working replica set there. 

#### Fourth run
With the same role config. Since the replica set is already initiated and it's config is distributes across all nodes, everything works fine. The `/etc/mongod.config` is updated with enabled auth and all `mongod`s are restarted.
And even this step can bring some errors because replica members should be configured on primary only.

---
I know this looks crazy, and it feels like this still can be automated via different "states" saved as local fact, but hardly I'll have time for this in the coming weeks.
Probably making a custom Ansible module which reads `mongod` config will be beneficial to let the role figure out what's happening on a particular node.
