### ISSUE TITLE
mongodb_version: "4.0" tries to install 4.4

### ISSUE THREAD

**Issue by sezanzeb** [UnderGreen/ansible-role-mongodb#260]
```yaml
- name: Install MongoDB
  include_role:
    name: undergreen.mongodb
  tags: [mongodb]
  vars:
    mongodb_version: "{{ MONGODB_VERSION }}"
    mongodb_package: "{{ MONGODB_PACKAGE }}"
    # ...
```

```ini
MONGODB_VERSION: "4.0"
MONGODB_PACKAGE: mongodb-org
```

`deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse` added to /etc/apt/sources.list.d

In the previous attempt the awx log showed something about 4.0, I can't find that log this time.

I don't know where to start to debug this
