### ISSUE TITLE
Dynamic host name

### ISSUE THREAD

**Issue by buunguyen** [UnderGreen/ansible-role-mongodb#35]
Hi, I looked at [your example](https://github.com/UnderGreen/ansible-playbook-mongodb/blob/master/host_vars%2F192.168.56.5.yml?ts=4) to define `mongodb_replication_params`. In my case, DB servers are provisioned dynamically in the playbook, so I can't hard-code the IPs. However, it looks like `host_name` expects the IP of the current host. If that's the case, can I use `ansible_eth0.ipv4.address` inside the playbook instead?  In other words, the definition would be:

```yml
mongodb_replication_params:
  - host_name: "{{ ansible_eth0.ipv4.address }}"
    host_port: "{{ mongodb_conf_port }}"
    host_type: replica
```

Is it the correct usage or do I misunderstand what `host_name` expects?
