### ISSUE TITLE
Error creating replica set

### ISSUE THREAD

**Issue by buunguyen** [UnderGreen/ansible-role-mongodb#36]
Hi, I'm having a problem setting up a 3-node replica set using this role on Ubuntu 14.04 servers.

The first run, I received these errors:
```bash
TASK: [greendayonfire.mongodb | Replication configuration] ********************
skipping: [db-2] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 2>'})
skipping: [db-3] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 3>'})
failed: [db-1] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 1>'}) => {"failed": true, "item": {"host_name": "<dedacted ip 1>", "host_port": "27017", "host_type": "replica"}}
msg: Unable to initiate replica set: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'<dedacted>'), ('key', u'<dedacted>')]) failed: auth failed
...ignoring

---

TASK: [greendayonfire.mongodb | Replication configuration] ********************
failed: [db-3] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 3>'}) => {"failed": true, "item": {"host_name": "<dedacted ip 3>", "host_port": "27017", "host_type": "replica"}}
msg: Unable to initiate replica set: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'<dedacted>'), ('key', u'<dedacted>')]) failed: auth failed
failed: [db-2] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 2>'}) => {"failed": true, "item": {"host_name": "<dedacted ip 2>", "host_port": "27017", "host_type": "replica"}}
msg: Unable to initiate replica set: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'<dedacted>'), ('key', u'<dedacted>')]) failed: auth failed
ok: [db-1] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 1>'})
```

In subsequent runs, I got these:

```bash
TASK: [greendayonfire.mongodb | Replication configuration] ********************
failed: [db-2] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 2>'}) => {"failed": true, "item": {"host_name": "<dedacted ip 2>", "host_port": "27017", "host_type": "replica"}}
msg: Unable to initiate replica set: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'<dedacted>'), ('key', u'<dedacted>')]) failed: auth failed
failed: [db-3] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 3>'}) => {"failed": true, "item": {"host_name": "<dedacted ip 3>", "host_port": "27017", "host_type": "replica"}}
msg: Unable to initiate replica set: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'<dedacted>'), ('key', u'<dedacted>')]) failed: auth failed
ok: [db-1] => (item={'host_port': u'27017', 'host_type': 'replica', 'host_name': u'<dedacted ip 1>'})
```

When I ssh to db-1 (the master), I can connect to the Mongo shell by supplying the `root` credentials (configured as part of this role). I also noticed that db-1 is a PRIMARY. However, login and connect the Mongo shell of db-2 and db-3 would result in an auth error. 

Below is my role configuration (those with default values are omitted):
```yml
mongodb_conf_auth: true
mongodb_conf_bind_ip: 0.0.0.0

mongodb_conf_replSet: myrs
mongodb_replication_params:
  - host_name: "{{ hostvars[inventory_hostname].ansible_eth0_1.ipv4.address }}" # private IP of the server
    host_port: "{{ mongodb_conf_port }}"
    host_type: replica

mongodb_root_admin_name: root
mongodb_root_admin_password: pwd
mongodb_user_admin_name: admin
mongodb_user_admin_password: pwd
mongodb_users:
  - {
    name: buu,
    password: pwd,
    roles: readWrite,
    database: mydb
}
mongodb_keyfile_content: |
  <dedacted key file content>

# the below is only set for db-1 group
mongodb_master: true
```

Any help is much appreciated.
