### ISSUE TITLE
Ansible complains about duplicate 'when' key in replication_init_auth.yml

### ISSUE THREAD

**Issue by David-Gil** [UnderGreen/ansible-role-mongodb#54]
Ansible complains about duplicate 'when' key. It then only uses the last defined value.
```
[WARNING]: While constructing a mapping from
/home/david/devel/ansible/playbooks/roles/dgilo.greendayonfire.mongodb/tasks/replication_init_auth.yml, line 23, column
3, found a duplicate dict key (when).  Using last defined value only.
```

```
- name: Replication configuration
  mongodb_replication:
    login_host: "{{ mongodb_login_host|default('localhost') }}"
    login_port: "{{ mongodb_conf_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port|default(27017) }}"
    host_type: "{{ item.host_type|default('replica') }}"
    hidden: "{{ item.hidden|default(false) }}"
    priority: "{{ item.priority|default(1.0) }}"
  when: mongodb_replication_params is defined
  with_items:
    - "{{ mongodb_replication_params|default([]) }}"
  when: mongodb_replica_init|failed
```
Ansible version:
```
david@dgilo:~/devel/ansible/playbooks/roles$ ansible --version
ansible 2.1.0 (devel edab8d338d) last updated 2016/04/06 14:56:43 (GMT +200)
  lib/ansible/modules/core: (detached HEAD cf01087a30) last updated 2016/04/05 12:01:07 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 204b4bab56) last updated 2016/04/05 12:01:07 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
