### ISSUE TITLE
mongodb_replication_params convertation

### ISSUE THREAD

**Issue by ivanursul** [UnderGreen/ansible-role-mongodb#72]
Hi. I'd like to create a replications from list of groups, that I've defined earlier.
So, let's say, I have a group called groups['mongodb-replica']
How can I pass them to mongodb_replication_params?
Thanks in advance.

**Comment by UnderGreen** [comment]
Hmm.. very interesting Ansible challenge. Accepted!

**Comment by ivanursul** [comment]
I'd be very happy, if you could also update the README.md
PS - I'm pretty new in Ansible, and you mongo package is the healthier. Thank you.

**Comment by UnderGreen** [comment]
You can write this code before usage of my role. It's just a Proof of Concept, I am don't have a free time to test it, but this code should work. 
```yaml
- hosts: all
  tasks:
    - name: get facts about ip addresses
      setup:
        filter: ansible_default_ipv4

   - name: set mongodb_replication_params variable
     set_facts:
       mongodb_replication_params:
         - host_name: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
           host_type: "{{ replica if 'mongodb-replica' in group_names else arbiter }}"
     with_items: 
        - "{{ groups['mongodb-replica'] }}"
        - "{{ groups['mongodb-arbiter'] }}" 
```
set_fact create dynamic facts and you should use this code all time, when you want to use my role. For persistent variables you should use variables in playbook or [local facts](http://docs.ansible.com/ansible/playbooks_variables.html#local-facts-facts-d).

**Comment by ivanursul** [comment]
I got

```
ERROR! 'set_facts' is not a valid attribute for a Task

The error appears to have been in '/Users/ivanursul/git/pet/queued/infrastructure/playbook-mongo-replica-bootstrap.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        filter: ansible_default_ipv4
    - name: "set mongodb_replication_params variable"
      ^ here
```

**Comment by UnderGreen** [comment]
Sure, `set_fact`, not a set_facts.

**Comment by ivanursul** [comment]
Now I have

```
ERROR! conflicting action statements

The error appears to have been in '/Users/ivanursul/git/pet/queued/infrastructure/playbook-mongo-replica-bootstrap.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        filter: ansible_default_ipv4
    - name: "set mongodb_replication_params variable"
      ^ here


The error appears to have been in '/Users/ivanursul/git/pet/queued/infrastructure/playbook-mongo-replica-bootstrap.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        filter: ansible_default_ipv4
    - name: "set mongodb_replication_params variable"
      ^ here
```


```
---
- hosts: all
  tasks:
    - name: "get facts about ip addresses"
      setup:
        filter: ansible_default_ipv4
    - name: "set mongodb_replication_params variable"
      set_fact:
        mongodb_replication_params:
          - host_name: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
            host_type: "{{ replica if 'mongodb-replica' in group_names else arbiter }}"
      with_items:
        - "{{ groups['mongodb-replica'] }}"
        - "{{ groups['mongodb-arbiter'] }}"
      debug: msg="echo it"
```

**Comment by ivanursul** [comment]
Looks good. Can we chat in skype or somewhere else ? mine skype is iursul

**Comment by ivanursul** [comment]
So I included it to my main mongo master

```
- hosts: app-mongodb
  become: yes
  become_method: sudo
  roles:
    - greendayonfire.mongodb
  vars:
    mongodb_security_authorization: "enabled"
    mongodb_replication_params: "{{ mongodb_replication_params }}"
    mongodb_users:
      - {
        name: user,
        password: ****,
        roles: readWrite,
        database: dbname
    }
```

And after I'm getting

```
TASK [greendayonfire.mongodb : Replication configuration | 2nd Pt] *************
fatal: [146.185.149.62]: FAILED! => {"failed": true, "msg": "{{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: {{ mongodb_replication_params }}: recursive loop detected in template string: {{ mongodb_replication_params }}"}
```

**Comment by ivanursul** [comment]
```
TASK [greendayonfire.mongodb : Replication configuration | 1st Pt.] ************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: {{ 
mongodb_replication_params_from_groups }}: 'mongodb_replication_params_from_groups' is undefined.
This feature will be removed in 
a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

```
---
- hosts: mongodb-replica
  tasks:
    - name: "get facts about ip addresses"
      setup:
        filter: ansible_default_ipv4
    - name: "set mongodb_replication_params_from_groups variable"
      set_fact:
        mongodb_replication_params_from_groups:
          - host_name: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
            host_type: "replica"
      with_items:
        - "{{ groups['mongodb-replica'] }}"
    - name: echo vars
      debug: msg = "{{ item }}"
      with_items: "{{ mongodb_replication_params_from_groups }}"

- hosts: mongodb
  become: yes
  become_method: sudo
  roles:
    - greendayonfire.mongodb
  vars:
    mongodb_security_authorization: "enabled"
    mongodb_replication_params: "{{ mongodb_replication_params_from_groups }}"
    mongodb_users:
      - {
        name: ****,
        password: ****,
        roles: readWrite,
        database: ****
    }
```

Please advise.

**Comment by ivanursul** [comment]
For those, who will hit the same proble, just change `mongodb_replication_params: "{{ mongodb_replication_params_from_groups }}"` to `mongodb_replication_params: mongodb_replication_params_from_groups`

**Comment by UnderGreen** [comment]
Hey,

you don't need variable `mongodb_replication_params` here ->
```yaml
vars:
    mongodb_replication_params: "{{ mongodb_replication_params_from_groups }}"
```
because set_fact did the trick for you, as I wrote before. Delete this variable and use my snippet as is.

**Comment by ivanursul** [comment]
Ah, I got the logic.
I think the issue is with other things. When I finished installing, I received
```
{ "ok" : 0, "errmsg" : "not running with --replSet", "code" : 76 } 
```
while executing rs.conf() command on master node.

**Comment by UnderGreen** [comment]
yes, I wrote about whis variable in README. You should set this var.

**Comment by lkievit** [comment]
set_fact in combination with with_items does not give me the right results: it just sets the fact multiple times, each time to the next value in the loop.

I have this working now using a json template:

```yaml
    - name: determine which ethernet interface holds the ip we want to use in mongo
      set_fact:
        eth_interface: "ansible_eth1"
      when: stage == "development"
    - name: determine which ethernet interface holds the ip we want to use in mongo
      set_fact:
        eth_interface: "ansible_eth0"
      when: stage != "development"
    - name: determine who is the master
      set_fact:
        mongodb_masternode: "{{ groups['mongodb-datastore'][0] }}"
    - name: determine the master ip
      set_fact:
        mongodb_masternode_ip: "{{ hostvars[mongodb_masternode][eth_interface]['ipv4']['address'] }}"
    - name: echo mongodb_masternode ip
      debug: msg={{ mongodb_masternode_ip }}
    - name: determine own ip
      set_fact:
        own_ip: "{{ ansible_eth1.ipv4.address }}"
      when: stage == "development"
    - name: determine own ip
      set_fact:
        own_ip: "{{ ansible_eth0.ipv4.address }}"
      when: stage != "development"
    - name: echo my ip
      debug: msg={{ own_ip }}
    - name: test if this machine is not the master
      set_fact:
        mongodb_master: false
      when: mongodb_masternode_ip != own_ip
    - name: test if this machine is the master
      set_fact:
        mongodb_master: true
      when: mongodb_masternode_ip == own_ip

    - name: Build replication json config
      set_fact:
        replication: "{{ lookup('template', 'mongodb_replication_params.j2') }}"
        # note that we build a _string_ here containing json, not a json object
      vars:
        hosts: "{{ groups['mongodb-datastore'] + groups['mongodb-arbiter'] }}"
    - name: echo replication
      debug: msg={{ replication }}

    - name: Convert replication json to an ansible variable mongodb_replication_params
      set_fact:
        mongodb_replication_params: "{{ replication|from_json }}"

    - name: echo mongodb_replication_params
      debug: msg={{ mongodb_replication_params }}

```
The template used to gather the hosts into a json string has the following contents:

```
"[{% for host in hosts %}{ \"host_name\": \"{{hostvars[host][eth_interface]['ipv4']['address']}}\", \"host_type\": \"{%
     if 'arbiter' in hostvars[host].ansible_hostname %}arbiter{% else %}replica{%
     endif %}\" }{% if not loop.last %},{% endif %}{% endfor %}]"
```
